### ISSUE TITLE
Extreme gender bias and sexism in Implementations & Methods documentations

### ISSUE THREAD

**Issue by BigBoneDaddy** [ark-lang/ark-docs#3]
The "Implementations & Methods" https://github.com/ark-lang/ark-docs/blob/master/REFERENCE.md#implementations-&-methods docs have extreme gender bias. There is struct Person and it has a gender: Gender field. But it only has 1 Gender field! It is known fact that gender is not binary and some people even have more than 1 gender and some people even have 0 gender or even negative gender. The documentations should not promote gender bias and sexism! The struct Person should support negative genders or 0 genders or 1 gender or more than 1 gender.

**Comment by felixangell** [comment]
Okay, you have been extremely persistent, and weren't sure if you are serious about any of this, but now it's really clear.

**Comment by raoulvdberge** [comment]
Bye, troll.
